# Deployment mode: SingleBinary (simple), SimpleScalable (medium), Distributed (large)
deploymentMode: SimpleScalable

# Component replicas
write:
  replicas: 2
read:
  replicas: 2
backend:
  replicas: 1

# Caching
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Helm test
test:
  enabled: false

# All loki settings combined under one key
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/chunks
  useTestSchema: true
