apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-app-deploy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-app
  template:
    metadata: 
      labels:
        app: latency-app
    spec:
      containers:
        - name: latency-app
          image: tz20123/http-echo-latency
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app-deploy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-app
  template:
    metadata: 
      labels:
        app: logging-app
    spec:
      containers:
        - name: logging-app
          image: mingrammer/flog:0.4.3
          args:
          - --loop
          - --number=10  # number of log lines per second
          - --delay=500ms
---

