apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-node-alerts
  namespace: monitoring # change this if you're using another namespace
  labels:
    role: alert-rules
spec:
  groups:
    - name: node_alerts
      rules:
        - alert: HighMemoryUsage
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage on {{ $labels.instance }}"
            description: "Memory usage is above 80% for more than 2 minutes."

        - alert: DiskPressure
          expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Disk pressure on node {{ $labels.node }}"
            description: "Node {{ $labels.node }} is under disk pressure."

        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod crash looping in {{ $labels.namespace }}"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} restarted more than 3 times in 5 minutes."
