apiVersion: v1
kind: Service
metadata:
  name: latency-app
  namespace: monitoring
  labels:
    app: latency-app
spec:
  selector:
    app: latency-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP
