deploymentMode: SingleBinary

singleBinary:
  replicas: 1

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false

test:
  enabled: false

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki

  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/chunks

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  limits_config:
    retention_period: 168h # 7 days

# promtail:
#   enabled: true

#   image:
#     tag: 3.4.3

#   extraVolumes:
#     - name: log-storage
#       persistentVolumeClaim:
#         claimName: logs-volume

#   extraVolumeMounts:
#     - name: log-storage
#       mountPath: /var/log

#   config:
#     server:
#       http_listen_port: 9080
#       grpc_listen_port: 0
#       log_level: info

#     positions:
#       filename: /tmp/positions.yaml

#     clients:
#       - url: http://loki:3100/loki/api/v1/push
#         tenant_id: fake  # Adds X-Scope-OrgID header

#     scrape_configs:
#       - job_name: kubernetes-logging-app
#         kubernetes_sd_configs:
#           - role: pod
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_label_app]
#             action: keep
#             regex: logging-app
#           - source_labels: [__meta_kubernetes_namespace]
#             action: keep
#             regex: monitoring
#           - source_labels: [__meta_kubernetes_namespace]
#             target_label: namespace
#           - source_labels: [__meta_kubernetes_pod_name]
#             target_label: pod
#           - source_labels: [__meta_kubernetes_pod_container_name]
#             target_label: container

#       - job_name: generated-logs
#         static_configs:
#           - targets:
#               - localhost
#             labels:
#               job: generated-logs
#               __path__: /var/log/generated-logs.txt
#         pipeline_stages:
#           - json:
#               expressions:
#                 http_method: method
#                 http_status: status
#           - labels:
#               http_method:
#               http_status:

