apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: latency-app
  labels:
    release: prometheus # matches your prometheus helm release label
spec:
  selector:
    matchLabels:
      app: latency-app
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
